# Generated by Django 6.0.6 on 2026-06-27 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("lifeos_app", "0003_executionitem_workspacecontainer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionitem",
            name="is_pinned",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="executionitem",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                db_index=True,
                default="Medium",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="executionitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Inbox", "Inbox"),
                    ("Backlog", "Backlog"),
                    ("Planned", "Planned"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                db_index=True,
                default="Inbox",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="executionitem",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="executionitem",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
