# Generated by Django 6.0.6 on 2026-06-27 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifeos_app", "0004_executionitem_is_pinned_executionitem_priority_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("achieved_date", models.DateField(blank=True, null=True)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                ("pdus_required", models.PositiveIntegerField(default=0)),
                ("pdus_earned", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DomainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_academy", models.BooleanField(default=False)),
                ("color", models.CharField(default="#9966CC", max_length=7)),
                ("icon", models.CharField(default="folder", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="GoogleCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calendar_id", models.CharField(max_length=255)),
                ("name", models.CharField(default="Primary", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="appsettings",
            name="auto_detect_location",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="dashboard_card_names",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="location_name",
            field=models.CharField(default="Seattle, WA", max_length=255),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="timezone",
            field=models.CharField(default="UTC", max_length=100),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="use_24h_time",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="use_imperial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="executionitem",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="executionitem",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="executionitem",
            name="extra_actual_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="executionitem",
            name="fuzzy_timeframe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Today", "Today"),
                    ("Tomorrow", "Tomorrow"),
                    ("Weekend", "Coming Weekend"),
                    ("Week", "This Week"),
                    ("Month", "This Month"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="executionitem",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="executionitem",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="lifeos_app.domaincategory",
            ),
        ),
        migrations.AddField(
            model_name="workspacecontainer",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containers",
                to="lifeos_app.domaincategory",
            ),
        ),
        migrations.CreateModel(
            name="NotionIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notion_page_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "notion_token",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "execution_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notion_link",
                        to="lifeos_app.executionitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurringConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Annually", "Annually"),
                            ("Custom", "Custom"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "custom_times_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "custom_period",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "execution_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence",
                        to="lifeos_app.executionitem",
                    ),
                ),
            ],
        ),
    ]
