# Generated by Django on 2026-06-26

from django.db import migrations

def populate_domains_and_link(apps, schema_editor):
    DomainCategory = apps.get_model('lifeos_app', 'DomainCategory')
    WorkspaceContainer = apps.get_model('lifeos_app', 'WorkspaceContainer')
    ExecutionItem = apps.get_model('lifeos_app', 'ExecutionItem')

    defaults = [
        {'name': 'Tech/Career', 'color': '#0F52BA', 'icon': 'briefcase', 'is_academy': False},
        {'name': 'Theater', 'color': '#E0115F', 'icon': 'mask', 'is_academy': False},
        {'name': 'Academy', 'color': '#9966CC', 'icon': 'academic-cap', 'is_academy': True},
        {'name': 'Home', 'color': '#50C878', 'icon': 'home', 'is_academy': False},
        {'name': 'Governance/Compliance', 'color': '#F59E0B', 'icon': 'scale', 'is_academy': False},
    ]

    domain_objs = {}
    for d in defaults:
        obj, _ = DomainCategory.objects.get_or_create(
            name=d['name'],
            defaults={'color': d['color'], 'icon': d['icon'], 'is_academy': d['is_academy']}
        )
        domain_objs[d['name']] = obj

    # Link WorkspaceContainer instances
    for container in WorkspaceContainer.objects.all():
        if container.domain_category in domain_objs:
            container.domain = domain_objs[container.domain_category]
            container.save()

    # Link ExecutionItem instances
    for item in ExecutionItem.objects.all():
        if item.domain_category in domain_objs:
            item.domain = domain_objs[item.domain_category]
            item.save()

def rollback_domains_and_link(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('lifeos_app', '0005_certification_domaincategory_googlecalendar_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_domains_and_link, rollback_domains_and_link),
    ]
