# Generated by Django 6.0.6 on 2026-06-29 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifeos_app", "0009_remove_appsettings_slm_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="credit_unit_type",
            field=models.CharField(default="Hours", max_length=50),
        ),
        migrations.AddField(
            model_name="certification",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="provider",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="executionitem",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workspacecontainer",
            name="certification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containers",
                to="lifeos_app.certification",
            ),
        ),
        migrations.AddField(
            model_name="workspacecontainer",
            name="credits_earned",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
