# Generated by Django 6.0.6 on 2026-06-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifeos_app", "0010_certification_credit_unit_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email associated with the calendar",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "credentials_json",
                    models.JSONField(
                        blank=True, help_text="Stored OAuth2 credentials", null=True
                    ),
                ),
                ("sync_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
