# Generated by Django 6.0.6 on 2026-06-29 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifeos_app", "0011_calendarintegration"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to="lifeos_app.domaincategory",
            ),
        ),
    ]
