# Generated by Django 6.0.6 on 2026-06-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifeos_app", "0012_tag_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="respect_child_dates_by_default",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="scheduler_buffer_minutes",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="theme_dark_start",
            field=models.TimeField(default="18:00:00"),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="theme_light_start",
            field=models.TimeField(default="06:00:00"),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="theme_mode",
            field=models.CharField(
                choices=[
                    ("Dark", "Dark"),
                    ("Light", "Light"),
                    ("Auto-Telemetry", "Auto-Telemetry"),
                    ("Auto-Schedule", "Auto-Schedule"),
                ],
                default="Dark",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="workspacecontainer",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspacecontainer",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspacecontainer",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
