# Generated by Django 6.0.6 on 2026-07-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("lifeos_app", "0013_appsettings_respect_child_dates_by_default_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="executionitem",
            index=models.Index(
                fields=["is_completed", "is_deleted", "is_archived", "status"],
                name="lifeos_app__is_comp_c700b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="executionitem",
            index=models.Index(
                fields=["start_date", "is_completed", "is_deleted"],
                name="lifeos_app__start_d_9d0f35_idx",
            ),
        ),
    ]
