# Generated by Django 6.0.6 on 2026-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifeos_app", "0014_executionitem_lifeos_app__is_comp_c700b1_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettings",
            name="theme_mode",
            field=models.CharField(
                choices=[
                    ("Dark", "Dark"),
                    ("Light", "Light"),
                    ("Solarized Light", "Solarized Light"),
                    ("Solarized Dark", "Solarized Dark"),
                    ("Auto-Telemetry", "Auto-Telemetry"),
                    ("Auto-Schedule", "Auto-Schedule"),
                ],
                default="Dark",
                max_length=50,
            ),
        ),
    ]
