# Generated by Django 6.0.7 on 2026-07-09 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomodoro_duration', models.PositiveIntegerField(default=25)),
                ('start_of_work_day', models.TimeField(default='09:00:00')),
                ('timezone', models.CharField(default='America/Phoenix', max_length=64)),
                ('use_24h_time', models.BooleanField(default=False)),
                ('use_imperial', models.BooleanField(default=True)),
                ('location_name', models.CharField(default='Phoenix, AZ', max_length=255)),
                ('latitude', models.FloatField(blank=True, default=33.66, null=True)),
                ('longitude', models.FloatField(blank=True, default=-112.34, null=True)),
                ('auto_detect_location', models.BooleanField(default=False)),
                ('priority_weight', models.FloatField(default=1.5)),
                ('urgency_weight', models.FloatField(default=2.0)),
                ('slm_endpoint', models.CharField(default='http://localhost:11434/api/generate', max_length=255)),
                ('enable_ai_scheduling', models.BooleanField(default=True)),
                ('respect_child_dates_by_default', models.BooleanField(default=True)),
                ('scheduler_buffer_minutes', models.PositiveIntegerField(default=10)),
                ('theme_mode', models.CharField(default='Dark', max_length=32)),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('notification_webhook_url', models.URLField(blank=True, default='')),
                ('notification_webhook_token', models.CharField(blank=True, default='', max_length=512)),
                ('reminder_lead_minutes', models.PositiveIntegerField(default=15)),
                ('reminder_second_lead_minutes', models.PositiveIntegerField(blank=True, default=1440, null=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('reminder_min_priority', models.IntegerField(choices=[(1, 'P1 - Critical / Blocking'), (2, 'P2 - High / Next Action'), (3, 'P3 - Normal / Routine'), (4, 'P4 - Low / Backlog')], default=3)),
                ('remind_backlog_with_due', models.BooleanField(default=False)),
                ('remind_inbox_with_due', models.BooleanField(default=False)),
                ('daily_completion_target', models.PositiveIntegerField(default=5)),
                ('daily_focus_minutes_target', models.PositiveIntegerField(default=120)),
                ('stability_streak_window_days', models.PositiveIntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='CalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('credentials_json', models.JSONField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('credits_required', models.FloatField(default=0)),
                ('credit_unit_type', models.CharField(default='CEU', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DomainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('color', models.CharField(default='#64748B', max_length=7)),
                ('icon', models.CharField(default='folder', max_length=50)),
                ('is_academy', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Domain categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('target_surface', models.CharField(choices=[('matrix', 'Matrix'), ('overview', 'Overview'), ('board', 'Board')], default='matrix', max_length=20)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StabilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('completions_count', models.PositiveIntegerField(default=0)),
                ('focus_seconds', models.PositiveIntegerField(default=0)),
                ('planned_minutes', models.PositiveIntegerField(default=0)),
                ('index_score', models.PositiveSmallIntegerField(default=0)),
                ('band', models.CharField(choices=[('STABLE', 'Stable'), ('BEHIND', 'Behind'), ('OVERLOADED', 'Overloaded')], default='STABLE', max_length=20)),
                ('streak_days', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('TASK', 'Task'), ('SUBTASK', 'Subtask'), ('LEARNING_TASK', 'Learning Task'), ('LIFE_ACTIVITY', 'Life Activity')], default='TASK', max_length=32)),
                ('status', models.CharField(choices=[('INBOX', 'Inbox'), ('BACKLOG', 'Backlog'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed')], default='INBOX', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'P1 - Critical / Blocking'), (2, 'P2 - High / Next Action'), (3, 'P3 - Normal / Routine'), (4, 'P4 - Low / Backlog')], default=3)),
                ('urgency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], default='NORMAL', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('fuzzy_timeframe', models.CharField(choices=[('NONE', 'None'), ('TODAY', 'Today'), ('TOMORROW', 'Tomorrow'), ('WEEKEND', 'Weekend'), ('THIS_WEEK', 'This Week'), ('THIS_MONTH', 'This Month')], default='NONE', max_length=20)),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('extra_actual_seconds', models.PositiveIntegerField(default=0)),
                ('stack_rank', models.PositiveIntegerField(default=0)),
                ('external_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='lifeos_app.executionitem')),
            ],
            options={
                'ordering': ['stack_rank', '-priority', 'due_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ItemDependencyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('BLOCKS', 'Blocks'), ('RELATES', 'Relates')], default='BLOCKS', max_length=20)),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_links_out', to='lifeos_app.executionitem')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_links_in', to='lifeos_app.executionitem')),
            ],
            options={
                'unique_together': {('from_item', 'to_item', 'link_type')},
            },
        ),
        migrations.AddField(
            model_name='executionitem',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependents', through='lifeos_app.ItemDependencyLink', to='lifeos_app.executionitem'),
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrule_text', models.CharField(blank=True, default='', max_length=255)),
                ('freq', models.CharField(blank=True, default='', max_length=20)),
                ('byweekday', models.CharField(blank=True, default='', max_length=64)),
                ('byhour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('next_occurrence_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('execution_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='lifeos_app.executionitem')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('score', models.FloatField(default=0)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('SOLVER', 'Solver'), ('CALENDAR_PUSH', 'Calendar Push')], default='MANUAL', max_length=20)),
                ('execution_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='lifeos_app.executionitem')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#A1A1AA', max_length=7)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='lifeos_app.domaincategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='executionitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='execution_items', to='lifeos_app.tag'),
        ),
        migrations.CreateModel(
            name='TimeAvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day_monday', models.BooleanField(default=True)),
                ('day_tuesday', models.BooleanField(default=True)),
                ('day_wednesday', models.BooleanField(default=True)),
                ('day_thursday', models.BooleanField(default=True)),
                ('day_friday', models.BooleanField(default=True)),
                ('day_saturday', models.BooleanField(default=False)),
                ('day_sunday', models.BooleanField(default=False)),
                ('start_time', models.TimeField(default='09:00:00')),
                ('end_time', models.TimeField(default='17:00:00')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_blocks', to='lifeos_app.domaincategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Cmd+K #token match key', max_length=255, unique=True)),
                ('container_type', models.CharField(choices=[('EPIC', 'Epic / Macro Project'), ('PROJECT', 'Project'), ('SPRINT', 'Development Sprint'), ('SPECIALIZATION', 'Academic Specialization'), ('COURSE', 'Academic Course'), ('MODULE', 'Course Module'), ('LIST', 'Operational List'), ('INBOX', 'Global Inbox')], default='PROJECT', max_length=32)),
                ('para_state', models.CharField(choices=[('PROJECT', 'Project (Active Velocity)'), ('AREA', 'Area (Maintenance)'), ('RESOURCE', 'Resource (Knowledge Vault)'), ('ARCHIVE', 'Archive (Frozen State)')], default='PROJECT', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'P1 - Critical / Blocking'), (2, 'P2 - High / Next Action'), (3, 'P3 - Normal / Routine'), (4, 'P4 - Low / Backlog')], default=3)),
                ('urgency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], default='NORMAL', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('external_url', models.URLField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=100)),
                ('credit_unit_type', models.CharField(blank=True, default='', max_length=32)),
                ('credits_earned', models.FloatField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='lifeos_app.certification')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='lifeos_app.domaincategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lifeos_app.workspacecontainer')),
                ('tags', models.ManyToManyField(blank=True, related_name='containers', to='lifeos_app.tag')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ItemContainerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_links', to='lifeos_app.executionitem')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='lifeos_app.workspacecontainer')),
            ],
        ),
        migrations.AddField(
            model_name='executionitem',
            name='containers',
            field=models.ManyToManyField(blank=True, related_name='execution_items', through='lifeos_app.ItemContainerLink', to='lifeos_app.workspacecontainer'),
        ),
        migrations.CreateModel(
            name='WorkspaceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('para_hint', models.CharField(blank=True, choices=[('PROJECT', 'Project (Active Velocity)'), ('AREA', 'Area (Maintenance)'), ('RESOURCE', 'Resource (Knowledge Vault)'), ('ARCHIVE', 'Archive (Frozen State)')], default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('domain_hint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='lifeos_app.domaincategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceTemplateNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('node_kind', models.CharField(choices=[('container', 'Container'), ('item', 'Item')], default='container', max_length=20)),
                ('container_type', models.CharField(blank=True, choices=[('EPIC', 'Epic / Macro Project'), ('PROJECT', 'Project'), ('SPRINT', 'Development Sprint'), ('SPECIALIZATION', 'Academic Specialization'), ('COURSE', 'Academic Course'), ('MODULE', 'Course Module'), ('LIST', 'Operational List'), ('INBOX', 'Global Inbox')], default='', max_length=32)),
                ('item_type', models.CharField(blank=True, choices=[('TASK', 'Task'), ('SUBTASK', 'Subtask'), ('LEARNING_TASK', 'Learning Task'), ('LIFE_ACTIVITY', 'Life Activity')], default='', max_length=32)),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lifeos_app.workspacetemplatenode')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='lifeos_app.workspacetemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('is_blocking', models.BooleanField(default=True)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lifeos_app.calendarintegration')),
            ],
            options={
                'indexes': [models.Index(fields=['start_at', 'end_at'], name='lifeos_app__start_a_18e37a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('end_reason', models.CharField(blank=True, choices=[('PAUSE', 'Pause'), ('STOP', 'Stop'), ('COMPLETE', 'Complete'), ('PREEMPTED', 'Preempted')], default='', max_length=20)),
                ('execution_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to='lifeos_app.executionitem')),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('execution_item',), name='uniq_open_focus_per_item')],
            },
        ),
        migrations.CreateModel(
            name='ReminderDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DUE_APPROACHING', 'Due Approaching'), ('ALLOCATION_START', 'Allocation Start'), ('OVERDUE', 'Overdue')], max_length=32)),
                ('fire_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(default='webhook_gotify', max_length=64)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SNOOZED', 'Snoozed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_dispatches', to='lifeos_app.executionitem')),
                ('scheduled_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_dispatches', to='lifeos_app.scheduledallocation')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'fire_at'], name='lifeos_app__status_86b86d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workspacecontainer',
            index=models.Index(fields=['slug'], name='lifeos_app__slug_7bff6d_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacecontainer',
            index=models.Index(fields=['container_type', 'para_state'], name='lifeos_app__contain_4ebf01_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcontainerlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('item',), name='uniq_primary_container_per_item'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcontainerlink',
            unique_together={('item', 'container')},
        ),
        migrations.AddIndex(
            model_name='executionitem',
            index=models.Index(fields=['status', 'is_deleted'], name='lifeos_app__status_f1d4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='executionitem',
            index=models.Index(fields=['due_at'], name='lifeos_app__due_at_826981_idx'),
        ),
        migrations.AddIndex(
            model_name='executionitem',
            index=models.Index(fields=['priority', 'urgency'], name='lifeos_app__priorit_a088ff_idx'),
        ),
    ]
