# Generated by Django 5.2 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifeos_app", "0008_theme_mode_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="openweather_api_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="weather_provider",
            field=models.CharField(
                choices=[
                    ("auto", "Auto (NWS in US, else Open-Meteo)"),
                    ("open_meteo", "Open-Meteo"),
                    ("nws", "NWS (weather.gov)"),
                    ("openweathermap", "OpenWeatherMap"),
                ],
                default="auto",
                max_length=20,
            ),
        ),
    ]
