# Generated by Django 5.2 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifeos_app", "0009_weather_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncedcalendar",
            name="display_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Show events on the Planner calendar grid (independent of sync).",
            ),
        ),
    ]
