# Generated by Django 5.2 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifeos_app", "0010_syncedcalendar_display_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="kp_band_blue_max",
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="kp_band_green_max",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="kp_band_yellow_max",
            field=models.FloatField(default=7.0),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="weather_band_cold_max",
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="weather_band_moderate_max",
            field=models.FloatField(default=75.0),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="weather_band_warm_max",
            field=models.FloatField(default=90.0),
        ),
    ]
