# Generated by Django 6.0.6 on 2026-07-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeos_app', '0013_container_extra_actual_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='microsoft_oauth_redirect_uri',
            field=models.CharField(blank=True, default='', help_text='Optional. Leave blank to auto-detect from the current site URL.', max_length=512),
        ),
    ]
