# Generated by Django 6.0.6 on 2026-08-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phronesis_app", "0026_scheduler_replan_horizon"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timetarget",
            name="uniq_time_target_tag_only",
        ),
        migrations.AlterField(
            model_name="domaincategory",
            name="icon",
            field=models.CharField(
                default="folder",
                help_text="Heroicons outline name (e.g. terminal, heart).",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="timetarget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("domain__isnull", True), ("tag__isnull", False)),
                fields=("tag",),
                name="uniq_time_target_tag_only",
            ),
        ),
    ]
